post_install() {
   DIR=/usr/share/pandoc/filters
   mkdir -p $DIR

   pkgs="$(xargs << EOF
b3/include-code-files
pandoc-ext/pretty-urls
pandoc-ext/pagebreak
pandoc-ext/abstract-section
pandoc-ext/list-table
pandoc-ext/diagram
tarleb/parse-latex
dialoa/statement
cdivita/pandoc-curly-switch
EOF
)"

   pushd $DIR
   for pkg in $pkgs; do
      git clone --depth 1 https://github.com/$pkg.git
   done
   popd
}
