#!/bin/bash

pkgs=$(grep -Po '/^\s*[(a-z)(A-Z)(0-9)\-\_]+(?=\s*#\s*aur)/d' PKGBUILD | sed 's/\s//g')

exit

pkgs=$(grep -Po '^\s*[(a-z)(A-Z)(0-9)\-\_]+(?=\s*#\s*aur)' PKGBUILD | sed 's/\s//g')

export PKGDEST="$(pwd)/repo"

if [[ ! -d aur ]]; then
   mkdir aur
fi
pushd aur

readDeps() {
   source $1/PKGBUILD
   echo ${depends[@]}
}

myMakepkg() {
   # download pkg if it has not been downloaded yet
   if [[ ! -d $1 ]]; then
      git clone --depth 1 https://aur.archlinux.org/$1.git
   fi

   # for all listed deps
   for dep in $(readDeps $1); do
      # if they are from aur: make those deps first
      if yay -Sai $dep > /dev/null; then
         myMakepkg $dep
      fi
   done
   # all deps have been built, now make the package itself
   pushd $1
   makepkg --syncdeps --noconfirm --sign
   popd # 1
}

for pkg in ${pkgs[@]}; do
   myMakepkg $pkg
done

unset PKGDEST
popd # aur
